version: '3'

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
        - ${PORT_DB}:5432

  web:
    build: .
    command: python /home/owerpy/Recipes/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/owerpy/Recipes/
    ports:
      - 8000:8000
    env_file:
      - .env
    links:
      - db
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local